In [14]:
import torch
import torch.nn as nn
from sklearn.datasets import make_multilabel_classification
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score, hamming_loss, accuracy_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter


In [2]:
X, y = make_multilabel_classification(n_samples=1000, n_features=20, n_classes=5, n_labels=2)

In [8]:
X

array([[3., 0., 4., ..., 2., 3., 1.],
       [5., 1., 3., ..., 1., 1., 5.],
       [6., 2., 2., ..., 1., 2., 3.],
       ...,
       [3., 2., 2., ..., 0., 3., 3.],
       [4., 5., 2., ..., 4., 4., 5.],
       [5., 2., 1., ..., 1., 0., 3.]], shape=(1000, 20))

In [9]:
y

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       ...,
       [1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0]], shape=(1000, 5))

In [10]:
X = torch.tensor(X, dtype=torch.float)
y= torch.tensor(y, dtype=torch.float)

In [11]:
X

tensor([[3., 0., 4.,  ..., 2., 3., 1.],
        [5., 1., 3.,  ..., 1., 1., 5.],
        [6., 2., 2.,  ..., 1., 2., 3.],
        ...,
        [3., 2., 2.,  ..., 0., 3., 3.],
        [4., 5., 2.,  ..., 4., 4., 5.],
        [5., 2., 1.,  ..., 1., 0., 3.]])

In [13]:
y

tensor([[1., 1., 1., 1., 1.],
        [1., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        ...,
        [1., 0., 0., 1., 0.],
        [0., 1., 0., 1., 0.],
        [0., 0., 0., 1., 0.]])

In [ ]:
BATCH_SIZE = 32


train_loader = DataLoader(
    trai
)

In [12]:
class Multilabel(nn.Module):
    def __init__(self, input_size, hidden_size, num_label):
        super(Multilabel, self).__init__()

        self.f1 = nn.Linear(input_size, hidden_size)
        self.relu1 = nn.ReLU()
        self.dropout1 = nn.Dropout(0.5)


        self.f2 = nn.Linear(hidden_size, hidden_size)
        self.relu2 = nn.ReLU()
        self.dropout2 = nn.Dropout(0.5)

        self.f3 = nn.Linear(hidden_size, num_label)


    def forward(self, x):
        x = self.dropout1(self.relu1(self.f1(x)))    
        x = self.dropout2(self.relu2(self.f2(x)))    
        x = self.f3(x)    

In [4]:
model = Multilabel(5,10,5)

In [7]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [ ]:
epochs = 1000

for epoch in range(epochs):
    model.train()

    for X_batch, y_batch in train_load